#:kivy 1.8.0
# 1: question
RootWidget:

    GridLayout:
        rows: 3
        cols: 1
        padding: 0
        spacing: 6

        Label:
            text: "Did you take your medication?"
            font_size: 60

        Button:
            text: 'YES'
            font_size: 90
            on_release: app.medsTaken('2')

        Button:
            text: 'NO'
            font_size: 90
            on_release: app.medsTaken('3')

